wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8000:80

wordpress_db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: examplepass

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8001:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass
